# Import Libraries

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense

Using TensorFlow backend.


# Create Train Data and Target Labels

In [2]:
training_data = np.array([[0,0],[0,1],[1,0],[1,1]])
target_data = np.array([[0],[0],[0],[1]])

# Train Model

In [11]:
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [12]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 16)                48        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 17        
Total params: 65
Trainable params: 65
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(training_data, target_data, epochs=1000)

Epoch 1/1000
4/4 [==============================] - 0s 98ms/step - loss: 0.6829 - accuracy: 0.5000
Epoch 2/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.6818 - accuracy: 0.5000
Epoch 3/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.6808 - accuracy: 0.5000
Epoch 4/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.6798 - accuracy: 0.5000
Epoch 5/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.6787 - accuracy: 0.5000
Epoch 6/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.6776 - accuracy: 0.5000
Epoch 7/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.6765 - accuracy: 0.5000
Epoch 8/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.6754 - accuracy: 0.5000
Epoch 9/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.6744 - accuracy: 0.5000
Epoch 10/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.6734 - accuracy: 0.5000
Epoch 11/1000
4/4 

In [15]:
score=model.evaluate(training_data, target_data)
print('Accuracy: ', score[1]*100)
print (model.predict(training_data).round())

4/4 [==============================] - 0s 1ms/step
Accuracy:  100.0
[[0.]
 [0.]
 [0.]
 [1.]]


# Weights

In [16]:
weights = model.get_weights()
weights

[array([[-0.85408723, -0.04989219, -0.07354116,  0.64506614, -0.0016611 ,
         -0.2127864 , -0.8239336 , -0.18522996,  0.93780637, -0.09183222,
          0.458334  , -0.38410074, -0.11780624, -1.1324502 , -0.03416348,
          0.71729577],
        [ 0.38951635, -0.49028462, -0.35512823, -1.3107109 , -0.06083733,
         -0.43602216,  0.4013463 , -0.43710768,  1.1465559 , -0.40280175,
          0.8239777 ,  0.18004009, -0.23899704,  0.48026574, -0.5622406 ,
          0.71701896]], dtype=float32),
 array([ 0.46464345,  0.        ,  0.        ,  0.6657633 , -0.01885882,
         0.6492906 ,  0.42265508,  0.67618316, -0.7214022 ,  0.        ,
        -0.45835143, -0.19064224,  0.703194  ,  0.65201813,  0.        ,
        -0.71698374], dtype=float32),
 array([[-1.1963851 ],
        [ 0.14852995],
        [ 0.22277373],
        [-0.8623384 ],
        [ 0.01280719],
        [-1.2783606 ],
        [-1.1800989 ],
        [-1.2207146 ],
        [ 1.3034215 ],
        [-0.4348179 ],
      

# Testing

In [17]:
test = np.array([[1,1],[0,1],[1,1],[1,1]])

In [18]:
print (model.predict(test).round())

[[1.]
 [0.]
 [1.]
 [1.]]
